# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: wisblock-for-zephyr
    west-commands: scripts/west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v3.3.0
      import: true
